//=====================================================
// This file was auto-generated by xlate_vreg v1.3
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    RTL_MAJOR
// Size:        32-bits
// Type:        Read/Write
// Description: "major" portion of RTL revision "major.minor.build"
//
#define RTL_MAJOR                                                    0x0000000000000000ULL


//
// Register:    RTL_MINOR
// Size:        32-bits
// Type:        Read/Write
// Description: "minor" portion of RTL revision "major.minor.build"
//
#define RTL_MINOR                                                    0x0000000000000004ULL


//
// Register:    RTL_BUILD
// Size:        32-bits
// Type:        Read/Write
// Description: "build" portion of RTL revision "major.minor.build"
//
#define RTL_BUILD                                                    0x0000000000000008ULL


//
// Register:    RTL_DATE
// Size:        32-bits
// Type:        Read/Write
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     month                          8   31:24 RO   N/A         Build month (1 thru 12)
//     day                            8   23:16 RO   N/A         Build date  (1 thru 31)
//     year                           16  15:00 RO   N/A         Build year  (4 digit year)
//
#define RTL_DATE                                                     0x0000000000000010ULL
#define RTL_DATE_month                                               0x0818000000000010ULL
#define RTL_DATE_day                                                 0x0810000000000010ULL
#define RTL_DATE_year                                                0x1000000000000010ULL


//
// Register:    RTL_TYPE
// Size:        32-bits
// Type:        Read/Write
// Description: Uniquely identifies this RTL design
//
#define RTL_TYPE                                                     0x0000000000000014ULL


//
// Register:    RTL_TIME
// Size:        32-bits
// Type:        Read/Write
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     hour                           8   23:16 RO   N/A         Build hour   (0 thru 23)
//     min                            8   15:08 RO   N/A         Build minute (0 thru 59)
//     sec                            8   07:00 RO   N/A         Build second (0 thru 59)
//
#define RTL_TIME                                                     0x000000000000001cULL
#define RTL_TIME_hour                                                0x081000000000001cULL
#define RTL_TIME_min                                                 0x080800000000001cULL
#define RTL_TIME_sec                                                 0x080000000000001cULL


//
// Register:    RTL_GIT_HASH
// Size:        This is an array of five consecutive 32-bit registers
// Type:        Read/Write
// Description: Git commit hash
//
#define RTL_GIT_HASH                                                 0x0000000000000040ULL


//
// Register:    REG_USE_SIM_DATA
// Size:        32-bits
// Type:        Read/Write
// Description: Set this to 1 to use simulated host-RAM data
//              Set this to 0 to use real data from host-RAM
//
#define REG_USE_SIM_DATA                                             0x0000000000001000ULL


//
// Register:    REG_HOST_FRAME_SIZE
// Size:        32-bits
// Type:        Read/Write
// Description: The size of a frame in host-RAM.
//
#define REG_HOST_FRAME_SIZE                                          0x0000000000001004ULL


//
// Register:    REG_FD_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: The base address of frame data in host-RAM.
//              Must be on a 4KB boundary
//
#define REG_FD_HOST_ADDR                                             0x4000000000001008ULL


//
// Register:    REG_FD_HOST_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: The size of the frame-data ring-buffer in host-RAM.
//              Must be a multiple of 8KB
//
#define REG_FD_HOST_SIZE                                             0x4000000000001010ULL


//
// Register:    REG_FRM_CONSUMED
// Size:        64-bits
// Type:        Read/Write
// Description: The number of frames of data consumed so far
//
#define REG_FRM_CONSUMED                                             0x4000000000001028ULL


//
// Register:    REG_START
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to this register to pre-fill the outgoing
//              FIFOs with data from host-RAM
//              This is cleared to zero by a reset
//
#define REG_START                                                    0x0000000000001038ULL


//
// Register:    REG_READY
// Size:        32-bits
// Type:        Read only
// Description: When this is non-zero, the system is ready to receive packet requests
//              After writing a 1 to REG_START, wait for REG_READY to be non-zero
//
#define REG_READY                                                    0x000000000000103cULL


//
// Register:    REG_RESET
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to this register to reset the system
//              Auto-clears to 0 when the reset operation is complete
//
#define REG_RESET                                                    0x0000000000001040ULL


//
// Register:    REG_SEND
// Size:        32-bits
// Type:        Read/Write
// Description: Write a value to this register to send that
//              number of packet-pairs
//              >>>>  FOR DEBUGGING ONLY <<<<
//
#define REG_SEND                                                     0x0000000000001044ULL


//
// Register:    REG_HBM0_TEMP
// Size:        32-bits
// Type:        Read only
// Description: The temperature in degrees C of HBM Bank 0
//
#define REG_HBM0_TEMP                                                0x0000000000001048ULL


//
// Register:    REG_HBM1_TEMP
// Size:        32-bits
// Type:        Read only
// Description: The temperature in degrees C of HBM Bank 1
//
#define REG_HBM1_TEMP                                                0x000000000000104cULL


//
// Register:    REG_SELFTEST_ERR
// Size:        32-bits
// Type:        Read only
// Description: Indicates a FIFO self-test failed
//              Bit  0 = Channel 0: Sequence check #0 failed
//              Bit  1 = Channel 0: Sequence check #1 failed
//              Bit  2 = Channel 0: Sequence check #2 failed
//              Bit  8 = Channel 1: Sequence check #0 failed
//              Bit  9 = Channel 1: Sequence check #1 failed
//              Bit 10 = Channel 1: Sequence check #2 failed
//
#define REG_SELFTEST_ERR                                             0x0000000000001050ULL


//
// Register:    REG_UW_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: The base address where userwave-data will be stored in host-RAM
//              Must be on a 4KB boundary
//
#define REG_UW_HOST_ADDR                                             0x4000000000002000ULL


//
// Register:    REG_UW_HOST_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: The size of the ring-buffer where userwave-data will be stored
//              in host-RAM.   Must be a multiple of 4KB
//
#define REG_UW_HOST_SIZE                                             0x4000000000002008ULL


//
// Register:    REG_UW_WRITTEN
// Size:        64-bits
// Type:        Read only
// Description: The number of 4KB blocks of userwave-data written to host RAM
//
#define REG_UW_WRITTEN                                               0x4000000000002010ULL


//
// Register:    REG_UW_DROPPED
// Size:        64-bits
// Type:        Read only
// Description: The number of 4KB blocks of userwave-data that were dropped
//
#define REG_UW_DROPPED                                               0x4000000000002018ULL


//
// Register:    REG_QSFP_SWAPPED
// Size:        32-bits
// Type:        Read only
// Description: If this is non-zero, the QSFP cables are swapped!
//
#define REG_QSFP_SWAPPED                                             0x0000000000002020ULL


//
// Register:    REG_LINK_STATUS
// Size:        32-bits
// Type:        Read only
// Description: Ethernet link status
//              Bit 0 = Link status of QSFP_0
//              Bit 1 = Link status of QSFP_1
//
#define REG_LINK_STATUS                                              0x0000000000002024ULL


//
// Register:    REG_CH0_MALFORMED
// Size:        32-bits
// Type:        Read only
// Description: The number of malformed packed received on QSFP_0
//
#define REG_CH0_MALFORMED                                            0x0000000000002028ULL


//
// Register:    REG_CH1_MALFORMED
// Size:        32-bits
// Type:        Read only
// Description: The number of malformed packed received on QSFP_1
//
#define REG_CH1_MALFORMED                                            0x000000000000202cULL



#endif
