connections = 
{
    /feeder/control/control/S_AXI  src/ecd_feeder/control.v       REG
    /axi_registers/S_AXI           src/ecd_feeder/axi_registers.v REG
    /pcie/axi_revision/S_AXI       src/common/axi_revision.v      RTL
}

